# Generated by Django 2.2.13 on 2021-07-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20210718_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autor_id',
            new_name='autor',
        ),
    ]
