# Generated by Django 2.2 on 2020-08-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0010_libro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad',
            field=models.SmallIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='libros/', verbose_name='Imagen Referencial'),
        ),
    ]
