# Generated by Django 2.2 on 2020-09-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0014_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad o Stock'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cantidad_dias',
            field=models.SmallIntegerField(default=7, verbose_name='Cantidad de Dias a reservar'),
        ),
    ]
