# Generated by Django 2.2 on 2020-09-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0015_auto_20200915_0659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
