# Generated by Django 2.2 on 2020-10-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0017_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento de reserva'),
        ),
    ]
