# Generated by Django 2.2 on 2020-10-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0021_remove_reserva_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento de la reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
