# Generated by Django 2.2 on 2020-06-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='permisos',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
