# Generated by Django 2.2 on 2020-06-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='permisos',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
