# Generated by Django 2.2 on 2020-06-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20200617_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_active',
            new_name='usuario_activo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_staff',
            new_name='usuario_administrador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
    ]
