# Generated by Django 2.2 on 2020-06-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20200617_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_administrador',
            new_name='is_staff',
        ),
    ]
