# Generated by Django 2.2 on 2020-07-17 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20200617_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('permiso_agregado', 'Permiso personalizado')]},
        ),
    ]
