# Generated by Django 2.2 on 2020-11-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_auto_20201105_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
